### ISSUE TITLE
status code 429 will be fiddled to 200 if no bufferlayer is used

### ISSUE THREAD

**Issue by JackySu** [benwis/tower-governor#8]
this is my main.rs:
```rust
#[tokio::main]
async fn main() {
    // ... my own implementation of initialization ...
    let governor = Box::new(
        GovernorConfigBuilder::default()
            .per_second(10)
            .burst_size(20)
            .use_headers()
            .finish()
            .unwrap(),
    );
    let app = Router::new()
        .route("/test", get(test))
        // ... my own middlewares and shared states ...
        .layer(
            ServiceBuilder::new()
                .layer(HandleErrorLayer::new(|e: BoxError| async move {
                    display_error(e)
                }))
                .layer(BufferLayer::new(1024)) // remove this will cause 429 too many requests fiddled to 200
                .layer(GovernorLayer {
                    config: Box::leak(governor),
                }),
        );

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::info!("Listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service_with_connect_info::<SocketAddr>())
        .await
        .unwrap();
```

if I put bufferlayer there everything works perfectly fine, if remove it then issue occurs, the 429 responses will be changed to 200, with an empty response body and no headers even if I enabled `use_headers()` when I set up governor config

I doubt this could be related to axum itself, but I'm not sure yet what happened

my Cargo.toml dependencies:
```toml
[dependencies]
dotenv = "0.15"
axum = { version = "0.6.18", features = ["ws", "json", "headers", "http2"] }
tower = { version = "0.4.13", features = ["buffer"] }
tower-http = { version = "0.4.3", features = ["fs", "trace", "util", "request-id", "sensitive-headers"], default-features = false }
tokio = { version = "1.28", features = ["full"] }
futures-util = { default-features = false, version = "0.3.28" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1.37", features = ["attributes"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1"
once_cell = "1"
postcard = { version = "1", features = ["use-std"] }
chrono = { version = "0.4", features = ["clock", "serde"] }
derivative = "2"
jsonwebtoken = "8"
tower_governor = { version = "*", features = ["tracing"] }
governor = "0.5.1"
http = "0.2.9"
```
